global using System;
global using System.Collections.Generic;
global using System.Linq;
global using NUnit.Framework;
global using OpenQA.Selenium;
global using DataDrivenTestingPatternTests.SecondVersion;
global using OpenQA.Selenium.Interactions;
global using OpenQA.Selenium.Support.UI;
global using SeleniumExtras.WaitHelpers;
